FROM mcr.microsoft.com/dotnet/sdk:5.0
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential
WORKDIR /app
COPY . .
RUN dotnet build
WORKDIR /app/DotnetTemplate.Web
ENTRYPOINT [ "dotnet",  "run"]