name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the C# code
      run: dotnet build
      
    - name: Run the C# tests
      run: dotnet test
      
    - name: Change directory
      run: cd DotnetTemplate.Web
      
    - name: Install npm # **From the DotnetTemplate.Web folder 
      run: npm install     
      
    - name: Build the typescript code # **From the DotnetTemplate.Web folder 
      run: npm run build
    
    - name: Run the linter on the typescript code # **From the DotnetTemplate.Web folder 
      run: npm run lint
  
    - name: Runs the typescript tests # **From the DotnetTemplate.Web folder 
      run: npm t