name: Helpful pipeline
on: [push]

jobs:
  build:
    name: Build and test and so on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.202
    - name: build
      run: dotnet build
    - name: test
      run: dotnet test

