name: Helpful pipeline
on: [push]

jobs:
  build:
    name: Build and test and so on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.202
    - name: build
      run: dotnet build
    - name: test
      id: test
      run: dotnet test
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: Build succeeded
    - name: commit-status-updater
      uses: ouzi-dev/commit-status-updater@v1.0.7
      status: success
    - name: commit-status-updater
      if: ${{ failure() }}
      uses: ouzi-dev/commit-status-updater@v1.0.7
      status: error
    - name: Slack Notify failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: Failed build! @everyone
        SLACK_LINK_NAMES: true

